### ISSUE TITLE
[BUG] First load: open settings = undefined json

### ISSUE THREAD

**Issue by Oricul** [aclist/kbin-kes#90]
**Describe the bug**
KES settings will appear (mostly) empty, and there are errors in console regarding undefined json.

**To Reproduce**
1. Remove KES' "Externals" and "Storage".
2. Visit a supported kbin instance.
3. Click KES' wrench icon.
4. Settings will be (mostly) empty.
5. Open console and you will see messages about undefined json.
6. Refresh the page (or navigate to a thread, etc.)
7. Open KES settings, and content will be present.

**Expected behavior**
Opening KES settings, even on first load, should load settings properly.

**Screenshots**
![Example](https://files.catbox.moe/vks0g5.png)

**KES version:**
- Tested in 2.0.3, but I would almost guarantee it's present prior to this too.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: LibreWolf (Firefox)
 - Browser version: 115.0.1-1
 - UserScript Manager: TamperMonkey

**Comment by aclist** [comment]
This is probably going to be fixed with the new patch, since the original safeGM implementation just naively remapped API calls to different names without actually handling async

**Comment by Oricul** [comment]
Good to hear. Let me know when testing branch has this fix and I'll confirm. It currently does not.

**Comment by aclist** [comment]
I'm just sitting down to untangle whatever it was I did yesterday, will update after the tea kicks in.

**Comment by aclist** [comment]
The patch is here: https://github.com/aclist/kbin-kes/pull/92

Unfortunately, some problems with TM, but it works on the other two. You'll also need to host the new safeGM somewhere and change the URL, since it's not currently merged in.

**Comment by Oricul** [comment]
It's merged on my fork/branch. I'll take a look to see what I can find.

**Comment by Oricul** [comment]
@artillect - What are you seeing as not working in TM?

**Comment by aclist** [comment]
Think you meant to reply to me? It was not loading in TM on the initial commit, but it was because I dropped the external resources from the header. I submitted a new change and it's working on TM as well, but something is awry with the wrench icon.

**Comment by aclist** [comment]
![a](https://github.com/aclist/kbin-kes/assets/92275929/9fadffc9-3aca-4649-9043-64021324ba52)

**Comment by aclist** [comment]
Regarding the initial bug, with this patch, tried deleting the externals from TM and force reloading, and the UI loads.

**Comment by Oricul** [comment]
Yes I totally did. Too tired this early (4:30A at time of comment). I'll update my branch and take a look at this. For me, everything was working.

**Comment by aclist** [comment]
Thanks. No worries. I think we have a nice raft of features going here with the [2.0.0 milestone](https://github.com/aclist/kbin-kes/milestone/3), once this blocking bug is fixed. Might have to ask a user with Safari to test the iOS thing, though.

**Comment by Oricul** [comment]
Which branch are you working out of? Wrench doesn't have issue after pulling in the latest https://github.com/aclist/kbin-kes/pull/92

**Comment by aclist** [comment]
Made a few typos in safeGM, but I'm still seeing the wrench issue after blowing away all of the externals and trying the script on a clean Firefox prefix (TamperMonkey)

**Comment by aclist** [comment]
The only changes between `main` and `testing` in the CSS: 

```
diff --git a/kes.css b/kes.css
index 52a0145..f4b33fe 100644
--- a/kes.css
+++ b/kes.css
@@ -1,16 +1,14 @@
 #kes-settings-button {
+	position: absolute;
 	top: 0;
 	right: 0;
 	margin: 0.5rem;
 	padding: 0.5rem;
 	color: var(--kbin-header-link-color);
+	font-size: 0.5em;
 	cursor: pointer;
 }
 
-#kes-settings:hover {
-	border-bottom: var(--kbin-header-hover-border);
-}
-
 #kes-settings-button:hover {
 	color: var(--kbin-header-link-hover-color);
 }
```

**Comment by Oricul** [comment]
@aclist - The issue is in the `@resource`. You're pulling it from `main` when you should pull from whatever branch you're in that contains the new button css.

**Comment by aclist** [comment]
Of course. Forehead slap moment. This is why I want to move to parameterized generation of the headers.

**Comment by aclist** [comment]
Do you get this jumping modal height issue when selecting categories, though?

https://github.com/aclist/kbin-kes/assets/92275929/bd212d63-9f58-4c95-a429-4bc5e8517448

**Comment by Oricul** [comment]
The video embed appears corrupt on my side?

**Comment by aclist** [comment]
I get that, too. Suffice to say that if you click on "General", which contains more mods than other pages, the height of the modal changes. This was apparently fixed in one of the early versions, but I think it got back in at some point. It's not related to this bug.

**Comment by Oricul** [comment]
Oh, like the entire modal increasing? Yeah - it's been like that for me since I installed KES after launch. Figured it was intended.

**Comment by aclist** [comment]
Right, got it. I think we talked about using overflow so the contents would scroll instead of being variable.

**Comment by aclist** [comment]
I've added a masthead autogen script that should do away with the aforementioned syntax problems and ensure all of the headers and consts are sane. (No need to manually declare requires or entrypoints in kes.user.js anymore)

**Comment by Oricul** [comment]
In [testing](https://github.com/aclist/kbin-kes/tree/testing), this bug is still present.

Regarding https://github.com/aclist/kbin-kes/issues/90#issuecomment-1635592167 , make sure TM settings are set to advanced, and re-open any previously opened userscripts. Once you've done that, you'll have a "storage" tab, replace the entire contents with `{}`, effectively like new, then reload page. Alternatively, wipe out KES completely, clear recycle bin, then try.

**Comment by aclist** [comment]
I've noticed it a few times, sporadically, but can't reproduce it every time by removing the externals. I believe this to be a race condition related to the way the JSON manifest is returned, although it looks like we are properly awaiting the response. Maybe it by the time the menu is ready to be opened the manifest is still missing, should wait longer. 

Does this happen if you reload and open the menu immediately, or after any amount of time has passed?

**Comment by Oricul** [comment]
[Here](https://files.catbox.moe/vmy4qq.mp4) is a video that may make it easier to understand.

**Comment by aclist** [comment]
I can't believe we didn't notice this sooner.

**Comment by aclist** [comment]
Made some changes in `2.0.0-rc.23` that should clear this on TamperMonkey/ViolentMonkey. Haven't grappled with the implications of this on GM and if it is happening there, though.

**Comment by Oricul** [comment]
Verified. Latest version does resolve the issue. I was sitting here working through it myself. Beat me to the punch. _**shakes fist**_

**Comment by aclist** [comment]
True, could probably just throw a momentary sleep in there and the problem would go away, but was trying to handle the `GM.` API's async methods correctly and wait on everything before proceeding. But I think our async implementation is not totally perfect right now. If you wanted to take a crack at that, be my guest.

**Comment by aclist** [comment]
Somewhere over the process between https://github.com/aclist/kbin-kes/blob/323bf11e67afc44a271707a550d78e327ad29f6b/kes.user.js, when all three were working, and the current version, that fixes the "empty menu" bug in this ticket, we managed to lose GM support again. It's like you said, when one works, the other doesn't. This is driving me crazy, and I'm beginning to suspect I need to wipe all extensions of their storage when performing these tests so that it doesn't get picked up by the wrong extension. To make matters worse, the JSON comes in parsed and unparsed flavors depending on what we are doing, so it makes the controlf low very annoying.

**Comment by Oricul** [comment]
In the current testing branch?

**Comment by aclist** [comment]
Yes RC 25 is working for this ticket on TM and VM, and the commit linked above was working for TM, VM, and GM originally, but when I go back to that commit, it doesn't seem to be working, which I'm scratching my head at, because the upstream files have not changed aside from the creation of a `/helpers` directory (which I accounted for when editing the old version).

**Comment by Oricul** [comment]
I see the issue. PR incoming.

**Comment by aclist** [comment]
Very nice. Thank you. And now, back to the salt mines.

**Comment by aclist** [comment]
I think this is pretty much good to go. I reworked the way payloads are handled and made the handling of the helper data more generic, then in the case of the GM. API, return everything as a single Promise and push it to the main function. Both the GM_ and GM. version pass a payload of unparsed JSON data to the main function, and the main function parses it before setting up the menus. In the case of GM_, it just doesn't do it asynchronously and fetches the resource as a bare string.

The only issue is the oddity of GM. extensions not catching the data on the first run. There is something strange in GM's implementation where for all intents and purposes, the Promise has cleared and the data is clearly available from internal storage by that point, but nothing until the second reload. I've tried zipping it back and forth through async and await calls (this is also a must for VM, as it rejects top-level await), but no dice. Maybe I am misunderstanding the documentation. Anyway, I took your suggestion and if, by the time we reach the menu rendering function, it can't find it, we `window.location.reload()`, and presto. This is...a kludge, but it should be nearly instantaneous and only affect the very first time the script is run, so seems tolerable (for now).

The net outcome is that it should work OOTB in all variants, while also solving the issue of a blank menu on first boot.

**Comment by aclist** [comment]
After thinking about it, I decided that just reloading the page here is potentially bad in the long-term. What if the remote resource is unavailable or the page is down? The user would be stuck in a loop of reloading. To cover both this case and potential future issues where for some reason, either the CSS, the manifest, or the UI cannot be obtained, I added a fallback logic that adds a small warning header to the top of the screen and then exits without proceeding to the rest of the KES logic. The header warns the user that the contents could not be fetched and advises reloading or trying again later.

This ensures that in the rare event that the resources are unreachable, the script won't try to proceed and produce unpredictable results. This was something we needed more generally. The CSS for this lives inside the script and acts as an emergency fallback.

![a](https://github.com/aclist/kbin-kes/assets/92275929/b6f7445b-6e64-4feb-9423-f5350ebf7cd6)
